We saw in the post https://www.studytonight.com/post/beginners-guide-to-numpy , how to create numpy arrays and powerful they are.Let us separately dive deeper with more examples.


# Different ways of creating numpy arrays:


## 1. Intuiative approach: using numpy.array():

Numpy arrays can be created very easily by passing a list in the function numpy.array().The python list when passed in this function gives us numpy array.

Let's import our favourite library **Numpy**:

In [2]:
import numpy as np # why writing numpy again & again , use power of 'as' keeping it concise and write np.

In [7]:
# making a python list li

li=[8,5,6,9,4,2]


# creating array out of it

numpy_array=np.array(li)

print(numpy_array)

[8 5 6 9 4 2]


We can also pass a list manually without explicitly writing it .

In [12]:
numpy_array=np.array([5,7,4,1,5,6])

Other arguments which are optional can also be included while creating the numpy arrays.One you might find useful further is:

->dtype: This argument specifies the data-type of the array created.Since, unlike lists all the elements in the numpy array are of same data-type.The dataypes ranging from float to complex, all are acceptable.

Let us see with an example:



In [14]:
numpy_array=np.array([1,8,5,59,8,98],dtype=float)
numpy_array

array([ 1.,  8.,  5., 59.,  8., 98.])

In [3]:
# let's try numpy array with string as input
string=['the','air','after','summer','rain']
arr=np.array(string)
arr

array(['the', 'air', 'after', 'summer', 'rain'], dtype='<U6')

In the similar manner other data-types can be used to create numpy array.

## 2. Using arange() function to create a numpy array:



The arange() function is one of the numpy's useful method used for creating an array within a specified range.The first arguement takes the starting point of the array you want to create, second is the stop point and third is the step.The last argument is again dtype which is optional.

arange(start,end,step,dtype)

Among all of the arguments only end is mandatory and by default start=0 and step=1.

In [18]:
# creating an array starting from 0 ending with 10 and increasing with a step of 2
arange_array=np.arange(0,11,2) # writing 11 instead of 10 since range is exclusive 
arange_array

array([ 0,  2,  4,  6,  8, 10])

Some more examples to make it crytsal clear:

In [17]:
arr1=np.arange(15) # starting from 0(by default),stopping at 14(don't forget 15 is exclusive),step=1 (by default)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# okaay now lets print backward counting:100 to 1
arr2=np.arange(100,0,-1)
arr2

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

## 3. linspace():


Like arange(), linspace can also be used to create numpy array but with more discipline.

In arange function we had some start,end and step points but with linspace() we can maintain a proper stepping .
Imagine when you have some arguments in arange() that your output array has elements not linearly stepped.In that case , linspace() comes to our rescue.


As arguments , linspace takes start index,end index and number of elements to be outputted.These number of elements would be linearly spaced in the range mentioned.

linspace(start_index,end_index,num_of_elements)

In [5]:
arr=np.linspace(15,75,10)
arr


array([15.        , 21.66666667, 28.33333333, 35.        , 41.66666667,
       48.33333333, 55.        , 61.66666667, 68.33333333, 75.        ])

## 4. empty():

Empty() function is used to create arrays when we don't really have any values to crate an array.What it does is , it takes the shape of the array desired and the array is created filled with random values.The trick here is without even using the random module we are able to build an array full of random values.Isn't that interesting?

empty(shape,dtype)

In [10]:
arr=np.empty((5,2),dtype=float) # arr of shape (5,2) with datatype=float filled with random values.
arr

array([[15.        , 21.66666667],
       [28.33333333, 35.        ],
       [41.66666667, 48.33333333],
       [55.        , 61.66666667],
       [68.33333333, 75.        ]])

## 5. Random modules,eye(),ones(),zeros(),identity():

Numpy arrays can also be created using the random module and it's functions like randn,randint etc.
We can also use some awesome functions to create array full of ones or zeros using np.ones(shape_of_array),np.zeros(shape_of_arrays).

We will explore these functions even more further in more tutorials.


Stay connected,stay curious and show some love.Don't forget to share (np.array(['sharing','is','caring']).